version: "2"
linters:
  enable:
    - depguard
    - misspell
    - revive
    - unconvert
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/containerd/containerd/errdefs
              desc: The containerd errdefs package was migrated to a separate module. Use github.com/containerd/errdefs instead.
            - pkg: github.com/containerd/containerd/log
              desc: The containerd log package was migrated to a separate module. Use github.com/containerd/log instead.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: redefines-builtin-id
    paths:
      - docs
      - images
      - out
      - script
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs
      - images
      - out
      - script
      - third_party$
      - builtin$
      - examples$
