name: Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
    - uses: actions/checkout@v4
    - name: Build all
      run: ./script/util/make.sh build -j2

  integration:
    runs-on: ubuntu-24.04
    name: Integration
    strategy:
      fail-fast: false
      matrix:
        buildargs: ["", "--build-arg=CONTAINERD_VERSION=main"] # released version & main version
        builtin: ["true", "false"]
        metadata-store: ["memory", "db"]
        exclude:
        - buildargs: ""
          builtin: "true"
        - metadata-store: "db"
          builtin: "true"
        - metadata-store: "db"
          buildargs: "--build-arg=CONTAINERD_VERSION=main"
    steps:
    - name: Install htpasswd for setting up private registry
      run: sudo apt-get update -y && sudo apt-get --no-install-recommends install -y apache2-utils
    - uses: actions/checkout@v4
    - name: Run integration test
      env:
        DOCKER_BUILD_ARGS: ${{ matrix.buildargs }}
        BUILTIN_SNAPSHOTTER: ${{ matrix.builtin }}
        METADATA_STORE: ${{ matrix.metadata-store }}
      run: make integration
