name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    name: Unit Tests with Coverage
    strategy:
      fail-fast: false
      matrix:
        module: [".", "./estargz", "./cmd", "./ipfs"]
        include:
          - module: "."
            name: "root"
          - module: "./estargz"
            name: "estargz"
          - module: "./cmd"
            name: "cmd"
          - module: "./ipfs"
            name: "ipfs"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Run unit tests with coverage
        run: |
          cd ${{ matrix.module }}
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.name }}
          path: ${{ matrix.module }}/coverage.txt

      - name: Check coverage threshold
        run: |
          cd ${{ matrix.module }}
          COVERAGE=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | sed 's/%//')
          echo "Total coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "Code coverage is below 50%"
            exit 1
          fi
